version: '3.7'
services:
  mongodb_container:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=RocoLib
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
